name: Django Admin Tests

on:
  push:
    branches:
      - django-admin
  pull_request:
    branches:
      - feature/home-view

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django_views

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Django check
        run: python manage.py check

      - name: Run tests
        run: pytest -q
